name: LegendsLib
version: '${version}'
author: TurboJax

api-version: '${minecraftVersion}'
main: org.turbojax.legendslib.LegendsLib

commands:
  legendslib:
    description: "The main command for Legends Lib"
    usage: "/legendslib help"
    aliases: [ll]